version: '3.9'

services:
  java_app:
    container_name: java_app
    image: firas/parkee:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5433/parkee
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=parkee123
    depends_on:
      db:
        condition: service_healthy
      
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=parkee123
      - POSTGRES_DB=parkee
      - PGPORT= 5433
    healthcheck:
      test: "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"
      interval: 10s
      timeout: 10s
      retries: 10

volumes:
  postgres_data: {}
